# Generated by Django 4.2.2 on 2023-06-12 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('max_val', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_val', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timmer', models.IntegerField()),
                ('track_time', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at_dt', models.DateTimeField()),
                ('last_check_at_dt', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
