# Generated by Django 4.2.2 on 2023-06-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_mymodel_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
