# Generated by Django 4.2.2 on 2023-06-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_stock_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_at_dt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_check_at_dt',
            field=models.CharField(max_length=255),
        ),
    ]
